name: Build and Deploy Python App to Azure Web App

env:
  AZURE_WEBAPP_NAME: ModernBertTextSentimentClassification  # Azure Web App name
  PYTHON_VERSION: '3.12'  # Python version

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ utilise Linux ici pour être cohérent avec Azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # ✅ Assure-toi que gunicorn et uvicorn sont bien installés
          pip install gunicorn uvicorn

      - name: Archive artifact for deployment
        run: |
          zip -r app.zip . -x "antenv/*"  # exclure le venv local du zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Unzip artifact
        run: unzip -o app.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
