name: Build and Deploy Python App to Azure Web App

env:
  AZURE_WEBAPP_NAME: ModernBertTextSentimentClassification  # 🔁 adapte ce nom si besoin
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List all files (recursive)
        run: ls -R

      - name: Debug: check if startup.sh is here
        run: find . -name "startup.sh"

      - name: Debug: check file permissions
        run: |
          if [ -f ./startup.sh ]; then
            ls -l ./startup.sh
          else
            echo "startup.sh not found in root directory"
          fi

      - name: Fix line endings (Windows to Unix)
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          if [ -f ./startup.sh ]; then
            dos2unix ./startup.sh
          fi

      - name: Make startup.sh executable
        run: |
          if [ -f ./startup.sh ]; then
            chmod +x ./startup.sh
          fi

      - name: Zip application
        run: |
          zip -r app.zip . -x "*.git*" "*__pycache__*" "*.venv/*" "venv/*" "myenv/*" ".github/*" "*.pytest_cache*" "*.mypy_cache*" ".vscode/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
